[package]
name = "mancala"
version = "0.1.0"
authors = ["bacef <mdn4993@rit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
